#!/bin/sh
#
# qdelweb
#
# Copyright (C) 2010, 2012 Universidad de Granada
# Authors: Leire López, Rafael Arco
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or (at
# your option) any later version.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

. /etc/profile.d/n1ge-6.2.sh

if [ $# -eq 1 ]; then
	qdel $1
else
    echo "Falta algún parámetro, para usar este script: "
    echo "$0 <jobid>"
    exit 1
fi
