#!/bin/sh
#
# qsub
#
# Copyright (C) 2010, 2012 Universidad de Granada
# Authors: Leire López, Rafael Arco
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or (at
# your option) any later version.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

if [ $# = '2' ]
then
. /etc/profile.d/n1ge-6.2.sh
/usr/local/apps/n1ge6_2_ib/bin/lx24-amd64/qsub -@ $1 $2
else
echo "Falta algún parámetro, para usar este script: "
echo "qsub <file_option_sge> <script_sge>"
fi

